name: poliedro_sistema
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0

  # Materiais (link/inline + opcional Storage)
  file_picker: ^10.3.2
  mime: ^2.0.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.3
  open_filex: ^4.4.0
  # Opcional (para quando quiser usar Storage de verdade)
  firebase_storage: ^13.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
