// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi8AjI6zAc4YOiDaYHKsrSB2NMb0zQIpQ',
    appId: '1:875888400081:web:d55173e7c7d9d0efd6d7f0',
    messagingSenderId: '875888400081',
    projectId: 'pi4semestre-a424d',
    authDomain: 'pi4semestre-a424d.firebaseapp.com',
    storageBucket: 'pi4semestre-a424d.firebasestorage.app',
    measurementId: 'G-BC054WLDBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1r7OSvLcJmHy4n95iAH8sEa0SJXIWTyc',
    appId: '1:875888400081:android:d6bfa241e197fcedd6d7f0',
    messagingSenderId: '875888400081',
    projectId: 'pi4semestre-a424d',
    storageBucket: 'pi4semestre-a424d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRapkk9-No20hUft44x9qB2YX03XDk52E',
    appId: '1:875888400081:ios:ecf20f4a696343ecd6d7f0',
    messagingSenderId: '875888400081',
    projectId: 'pi4semestre-a424d',
    storageBucket: 'pi4semestre-a424d.firebasestorage.app',
    iosBundleId: 'com.example.poliedroSistema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRapkk9-No20hUft44x9qB2YX03XDk52E',
    appId: '1:875888400081:ios:ecf20f4a696343ecd6d7f0',
    messagingSenderId: '875888400081',
    projectId: 'pi4semestre-a424d',
    storageBucket: 'pi4semestre-a424d.firebasestorage.app',
    iosBundleId: 'com.example.poliedroSistema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi8AjI6zAc4YOiDaYHKsrSB2NMb0zQIpQ',
    appId: '1:875888400081:web:a6e418dcb9c3db36d6d7f0',
    messagingSenderId: '875888400081',
    projectId: 'pi4semestre-a424d',
    authDomain: 'pi4semestre-a424d.firebaseapp.com',
    storageBucket: 'pi4semestre-a424d.firebasestorage.app',
    measurementId: 'G-LHRVWGDSKG',
  );
}
